apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-booking-service
  labels:
    app.kubernetes.io/name: argocd-booking-service
    app.kubernetes.io/part-of: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-booking-service
  labels:
    app.kubernetes.io/name: argocd-booking-service
    app.kubernetes.io/part-of: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-booking-service
subjects:
  - kind: ServiceAccount
    name: argocd-booking-service
    namespace: argocd
