apiVersion: v1
kind: Service
metadata:
  name: argocd-booking-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-booking-service
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-booking-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
